### PR TITLE
chore: repository governance

### PR DESCRIPTION
**Pull request by matt-FFFFFF**
## Repository governance update

This PR was automatically created by the AVM Team hive-mind using the [grept](https://github.com/Azure/grept) governance tool.

We have detected that some files need updating to meet the AVM governance standards.
Please review and merge with alacrity.

Grept config source: `git::https://github.com/Azure/Azure-Verified-Modules-Grept.git//terraform`

Thanks! The AVM team :heart:

### CODE REVIEW

**Comment by cshea-msft** [comment]
@matt-FFFFFF I pushed your PR but the docs command fails when its .17 and not .16. I have to manually fix it to .16

**Comment by matt-FFFFFF** [comment]
You're using old pipelines I think.

Need to change this back to 17 and have a look. Am about tomorrow

**Comment by cshea-msft** [comment]
this repo is at 17 but I created a new PR on Friday for FIrewall and it failed when I ran. Here is my comment here https://github.com/Azure/terraform-azurerm-avm-res-network-azurefirewall/pull/9#issuecomment-1934745598

**Comment by matt-FFFFFF** [comment]
Ahhh - sorry

What command are you running?

Should be avm docs using the docker container

**Pull request merged**
