### PR TITLE
updating typos 

### PR DESCRIPTION
**Pull request by cshea-msft**

### CODE REVIEW

**Comment by cshea-msft** [comment]
@matt-FFFFFF I think the errors are from the changes you been pushing? all I did in my code was change the version from 0.1.0 to 0.1.1 and changed two words in the variable comments.

**Comment by matt-FFFFFF** [comment]
Your release tags and names should be valid SEMVER v1.2.3 format.

Yours seeks to have a leading decimal.

**Comment by matt-FFFFFF** [comment]
If you look at the terraform lint failure you'll see is is complaining about use of heredoc. If you look at the same file in template repo we have fixed this issue and converted it to jsonencode().

**Comment by cshea-msft** [comment]
> If you look at the terraform lint failure you'll see is is complaining about use of heredoc. If you look at the same file in template repo we have fixed this issue and converted it to jsonencode().

when was that change? i published this two weeks ago and didn't get the issue. Do I have to go to the template and change it in my repo?

**Pull request merged**
